### ISSUE TITLE
Composer package

### ISSUE THREAD

**Issue by Jeckerson** [ismail0234/phalcon-bb-debugger#1]
Subject?

**Comment by ismail0234** [comment]
now the composer is not connected. I will add soon.

**Comment by ismail0234** [comment]
added composer. [#composer-install-files](https://github.com/ismail0234/phalcon-bb-debugger#composer-install-files)

**Comment by Jeckerson** [comment]
Also you add specific PHP module, in current case: `ext-phalcon`

```
    "require": {
    	"php": ">=5.5",
        "ext-phalcon": "^3"
    },
```

**Comment by ismail0234** [comment]
@Jeckerson thank you. my added.
